name: Android CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: gradle
      - run: chmod +x gradlew
      - run: ./gradlew build

  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: gradle
      - run: chmod +x gradlew
      - name: Run tests using Android Emulator Runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: adopt
      - run: chmod +x gradlew
      - run: echo y | sdkmanager --install "system-images;android-30;default;x86"
      - run: avdmanager create avd -n testAVD -k "system-images;android-30;default;x86" --force
      - run: |
          nohup emulator -avd testAVD -no-audio -no-window &
          sleep 60
      - run: ./gradlew connectedCheck
      - run: adb emu kill
      