name: Android CI

on:
  push:
    branches: ["*"]  
  pull_request:
    branches: ["*"]  

jobs:

   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

   test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

   build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: adopt
      - name: Download Android Command Line Tools
        run: |
          mkdir ~/.android && touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-*.zip -d ~/.android/
          rm commandlinetools-linux-*.zip
      - name: Install Android SDK Components
        run: |
          export ANDROID_SDK_ROOT=~/.android/cmdline-tools/latest
          yes | $ANDROID_SDK_ROOT/bin/sdkmanager --install "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;default;x86"
      - name: Accept Licenses
        run: |
          export ANDROID_SDK_ROOT=~/.android/cmdline-tools/latest
          yes | $ANDROID_SDK_ROOT/bin/sdkmanager --licenses
      - name: Create AVD
        run: |
          export ANDROID_SDK_ROOT=~/.android/cmdline-tools/latest
          $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd -n testAVD -k "system-images;android-30;default;x86" --force
      - name: Start emulator
        run: |
          export ANDROID_SDK_ROOT=~/.android/cmdline-tools/latest
          nohup $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD -no-audio -no-window &
          sleep 60
      - name: Run tests
        run: ./gradlew connectedCheck
      - name: Stop emulator
        run: adb emu kill

        